version: '3.8'

#Aquest codi estableix els fonaments de l'infraestructura de dades mitjançant la
# creació d'un magatzem central automatitzat. Mitjançant un fitxer de configuració de
# Docker Compose, el sistema aixeca un servidor local de MinIO, que actua com un "clon"
#d'Amazon S3 al propi ordinador per emmagatzemar i compartir els fitxers Parquet del
#dataset de l'NBA de forma eficient entre tots els membres de l'equip.

services:
  # Servei d'Emmagatzematge (El teu Rebost)
  minio:
    image: minio/minio
    container_name: nba_minio
    ports:
      - "9000:9000" # Port pel codi (API)
      - "9001:9001" # Port per a tu (Consola Web)
    environment:
      MINIO_ROOT_USER: "minioadmin"      # Usuari
      MINIO_ROOT_PASSWORD: "minioadmin"  # Contrasenya
    volumes:
      - ./minio_data:/data               # Persistència: les dades es guarden aquí
    command: server /data --console-address ":9001"
    networks:
      - nba_network

  mqtt:
    image: eclipse-mosquitto:2
    container_name: nba_mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./services/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    networks:
      - nba_network

  preprocess:
    build: ./services/preprocess
    container_name: nba_preprocess
    environment:
      MQTT_HOST: mqtt
      MQTT_PORT: 1883
      TOPIC_RAW: shots/raw
      TOPIC_CLEAN: shots/clean
      MQTT_QOS: 1
    depends_on:
      - mqtt
    restart: unless-stopped
    networks:
      - nba_network

  ingest:
    build: ./services/ingest
    container_name: nba_ingest
    environment:
      MQTT_HOST: mqtt
      MQTT_PORT: 1883
      TOPIC_RAW: shots/raw
      MQTT_QOS: 1

      # Hugging Face real dataset
      HF_DATASET: Vladislav/nba_dataset
      HF_SPLIT: train
      HF_STREAMING: "1"

      # Demo control (evita volverte loco con 70M filas)
      MAX_EVENTS: 5000
      SLEEP_MS: 0

      # Opcional: filtrar por año (ej. 2020-2020)
      # YEAR_MIN: "2020"
      # YEAR_MAX: "2020"
    depends_on:
      - mqtt
      - preprocess
    networks:
      - nba_network

networks:
  nba_network:
    driver: bridge